### ISSUE TITLE
Is this project still active? Or is there anything else like it?  Also, I saw some stuff about Windows?

### ISSUE THREAD

**Issue by Etrit1** [bijection/sistine#19]
Heya, this project looks super cool! but, there haven't been any updates since '18.

Does it still work?

Also, is it true that people used it on Windows? if so, how?

OR are there any alternative projects that make a windows Webcam into a touch screen?  (I'm sure there are but, knowing if there are any good ones would be primo! :-)

Thanks

**Comment by anishathalye** [comment]
This project is not actively maintained. It was written as a hack, not necessarily designed to be robust software for regular use.

> Does it still work?

Probably? It might require specific versions of dependencies if things have changed since 2016.

> Also, is it true that people used it on Windows? if so, how?

See here: https://github.com/bijection/sistine/blob/master/README_WINDOWS.MD. Note that we have not tested these instructions.
